version: '3.8' # Use a specific version for consistency

services:
  db:
    image: postgis/postgis:16-3.4 # Specific image: Postgres 16, PostGIS 3.4
    container_name: pg-tois # A friendly name for the container
    restart: unless-stopped # Or 'always' if you prefer
    environment:
      # These variables are used by the postgres image to initialize the DB
      # Use environment variables from a .env file (see next step) for security
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      # Mount a named volume to persist database data outside the container
      - pgdata:/var/lib/postgresql/data
      # Optional: Mount a directory for initialization scripts (see advanced section below)
      # - ./init-db:/docker-entrypoint-initdb.d
    ports:
      # Map host port 5432 to container port 5432
      # Change the host port (left side) if 5432 is already in use on your Mint PC
      - "127.0.0.1:5432:5432" # Only expose on localhost for security initially
      # Use "0.0.0.0:5432:5432" or just "5432:5432" to expose externally (be careful!)
    # Optional Healthcheck (Recommended)
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  # Define the named volume used above
  pgdata:
    # driver: local # default driver
